### PR TITLE
Prevent recursive calls for EnvoyData

### PR DESCRIPTION
**Pull request by mnederlof**
Hopefully this will prevent recursive calls more definitively, if they occur, we'd know sooner anyway.

### CODE REVIEW

**Comment by mnederlof** [comment]
Just removed the `__getattr__` method completely and updated appropriate calls. Please verify though 😇

**Comment by mnederlof** [comment]
One thing to remember, is that whenever a `AttributeError` is raised in a class, which has a `__getattr__` method defined in the class, python will call that method to see if it resolves to anything...

Have not verified in python how/where, it is just a observation. If we catch the `AttributeError` ourselves, we can do something else with it.

**Comment by vincentwolsink** [comment]
It is pretty hard to see now which calss used the magic getattr and which from regular class variables.
There is also a magic getattr in `EnvoyReader`. Should we remove it there too?

**Comment by mnederlof** [comment]
> It is pretty hard to see now which calls used the magic getattr and which are regular class variables. There is also a magic getattr in `EnvoyReader`. Should we remove it there too?

No not yet, i'm working on another PR that will remove that requirement as well, but that also implies some changes to the `__init__.py` file and how updates are handled.

**Comment by mnederlof** [comment]
> (Btw, if you create a PR from your own fork I cannot contribute to it without merging first.)

I'll start committing branches to your repo then 😄

**Review by vincentwolsink — APPROVED** [review]

**Comment by vincentwolsink** [comment]
I merged this one already, but there seems to be something wrong:
```
Traceback (most recent call last):
  File "/Users/vincent/devel/home_assistant_enphase_envoy_installer/custom_components/enphase_envoy/envoy_reader.py", line 350, in <module>
    class EnvoyStandard(EnvoyData):
  File "/Users/vincent/devel/home_assistant_enphase_envoy_installer/custom_components/enphase_envoy/envoy_reader.py", line 384, in EnvoyStandard
    @envoy_property(required_endpoint="endpoint_production_power")
  File "/Users/vincent/devel/home_assistant_enphase_envoy_installer/custom_components/enphase_envoy/envoy_reader.py", line 190, in envoy_property
    return prop(*a)
TypeError: prop() missing 1 required positional argument: 'f'
```

**Comment by mnederlof** [comment]
see #66

**Pull request merged**
