### PR TITLE
Add firmware status entity and relays

### PR DESCRIPTION
**Pull request by mnederlof**
I have two relays in my setup, which are also available through this newly discovered endpoint 😄 

And i already had a custom entity for firmware status of the envoy, so i just added this as well.

Unfortunately, the relays only report back if they are open/closed (and no voltage/hertz stats), but at least it's something.

The relays appear in both the pcu (where inverters live as well), and in the nsrb output, so they had to be filtered out in the `inverters_status` method.

Some example output from my env:
```json
{
    "counters": {
        "pcu": {
            "expected": 14,
            "discovered": 14,
            "ctrlsTotal": 14,
            "ctrlsGone": 0,
            "ctrlsCommunicating": 14,
            "chansTotal": 14,
            "chansRecent": 14,
            "chansProducing": 14
        },
        "acb": {
            "expected": 0,
            "discovered": 0,
            "ctrlsTotal": 0,
            "ctrlsGone": 0,
            "ctrlsCommunicating": 0,
            "chansTotal": 0,
            "chansRecent": 0,
            "chansProducing": 0
        },
        "nsrb": {
            "expected": 2,
            "discovered": 2,
            "ctrlsTotal": 2,
            "ctrlsGone": 0,
            "ctrlsCommunicating": 2,
            "chansTotal": 2,
            "chansRecent": 2,
            "chansProducing": 0
        },
        "pld": {
            "expected": 16,
            "discovered": 16,
            "ctrlsTotal": 16,
            "ctrlsGone": 0,
            "ctrlsCommunicating": 16,
            "chansTotal": 16,
            "chansRecent": 16,
            "chansProducing": 14
        },
        "esub": {
            "expected": 0,
            "discovered": 0,
            "ctrlsTotal": 0,
            "ctrlsGone": 0,
            "ctrlsCommunicating": 0,
            "chansTotal": 0,
            "chansRecent": 0,
            "chansProducing": 0
        }
    },
    "pcu": {
        "fields": ["serialNumber", "devType", "communicating", "recent", "producing", "reportDate", "temperature", "dcVoltageINmV", "dcCurrentINmA", "acVoltageINmV", "acPowerINmW"],
        "values": [
            ["123456789010", 1, true, true, true, 1683023261, 34, 31071, 3377, 236976, 198129],
            ["123456789012", 1, true, true, true, 1683023263, 28, 31204, 3397, 236576, 199061],
            ["123456789750", 1, true, true, true, 1683023265, 29, 31344, 2762, 237104, 186158],
            ["123456789983", 1, true, true, true, 1683023265, 34, 31069, 3382, 237048, 199176],
            ["123456789520", 1, true, true, true, 1683023268, 29, 31312, 2737, 237312, 184320],
            ["123456789983", 1, true, true, true, 1683023270, 25, 31507, 3192, 237240, 195689],
            ["123456789521", 1, true, true, true, 1683023271, 25, 31504, 3242, 237616, 197302],
            ["123456789669", 1, true, true, true, 1683023273, 25, 31425, 3252, 237520, 198788],
            ["123456789748", 1, true, true, true, 1683023275, 25, 31418, 3231, 236768, 197134],
            ["123456789985", 1, true, true, true, 1683023276, 26, 31435, 2713, 237184, 184904],
            ["123456789285", 1, true, true, true, 1683023279, 25, 31385, 3144, 237296, 197203],
            ["123456789246", 1, true, true, true, 1683023281, 25, 31399, 3197, 238328, 198656],
            ["123456789590", 1, true, true, true, 1683023280, 26, 31310, 3082, 238136, 196538],
            ["123456789862", 1, true, true, true, 1683023284, 27, 31653, 2714, 237728, 188057],
            ["123456789177", 12, true, true, false, 1683023285, 0, 0, 0, 0, 0],
            ["123456789944", 12, true, true, false, 1683023287, 0, 0, 0, 0, 0]
        ]
    },
    "acb": {
        "fields": ["serialNumber", "SOC", "minCellTemp", "maxCellTemp", "capacity", "totVoltage", "sleepEnabled", "sleepMinSoc", "sleepMaxSoc"],
        "values": []
    },
    "nsrb": {
        "fields": ["serialNumber", "relay", "forced", "reason_code", "reason", "line-count", "line1-connected", "line2-connected", "line3-connected"],
        "values": [
            ["123456789177", "closed", false, -1, "ok", 1, true, false, false],
            ["123456789944", "closed", false, -1, "ok", 1, true, false, false]
        ]
    }
}
```

### CODE REVIEW

**Comment by vincentwolsink** [comment]
Hi @mnederlof, thanks for your PR! 😃 I think you forgot to include changes to `BINARY_SENSORS` in `const.py`?

**Comment by mnederlof** [comment]
You were right.. how stupid of me. 😄

**Comment by vincentwolsink** [comment]
@mnederlof Can you maybe send me the output of your `home.json`? Or at least the `update_status` field. Because mine does not include the field and then this code shows an update is available.

**Comment by mnederlof** [comment]
Sure, here it is:
```json
{
	"software_build_epoch": 1642480978,
	"is_nonvoy": false,
	"db_size": 5427200,
	"db_percent_full": "  1.44",
	"timezone": "Europe/Amsterdam",
	"current_date": "05/03/2023",
	"current_time": "22:02",
	"network": {
		"web_comm": true,
		"ever_reported_to_enlighten": true,
		"last_enlighten_report_time": 1683144108,
		"primary_interface": "wlan0",
		"interfaces": [{
			"type": "ethernet",
			"interface": "eth0",
			"mac": "re:da:ct:ed:01:01",
			"dhcp": true,
			"ip": "169.254.120.1",
			"signal_strength": 0,
			"signal_strength_max": 1,
			"carrier": false
		}, {
			"signal_strength": 2,
			"signal_strength_max": 5,
			"type": "wifi",
			"interface": "wlan0",
			"mac": "re:da:ct:ed:01:01",
			"dhcp": true,
			"ip": "xx.xx.xx.xx",
			"carrier": true,
			"supported": true,
			"present": true,
			"configured": true,
			"status": "connected"
		}]
	},
	"tariff": "time_of_use",
	"comm": {
		"num": 2,
		"level": 0,
		"pcu": {
			"num": 0,
			"level": 0
		},
		"acb": {
			"num": 0,
			"level": 0
		},
		"nsrb": {
			"num": 2,
			"level": 5
		},
		"esub": {
			"num": 0,
			"level": 0
		},
		"encharge": [{
			"num": 0,
			"level": 0,
			"level_24g": 0,
			"level_subg": 0
		}]
	},
	"alerts": [],
	"update_status": "satisfied",
	"wireless_connection": [{
		"signal_strength": 0,
		"signal_strength_max": 0,
		"type": "zigbee",
		"connected": false
	}, {
		"signal_strength": 0,
		"signal_strength_max": 0,
		"type": "subghz",
		"connected": false
	}],
	"enpower": {
		"connected": false,
		"grid_status": "closed"
	}
}
```

**Comment by mnederlof** [comment]
Mine is a metered envoy btw, running fw D7.0.88

**Comment by vincentwolsink** [comment]
Merged. I adjusted the code a little bit to not show the Firmware status when the field is not available in home.json.
Can you check if `0.1.7-beta1` works for you @mnederlof ?

**Comment by mnederlof** [comment]
Yup, those changes work just fine here!

**Pull request merged**
