### PR TITLE
Prevent negative production values, for small negative

### PR DESCRIPTION
**Pull request by mnederlof**
When the CT is logically wired behind the Relay, it will measure about 3.5 watts of usage per relay. So a small relay usage when the sun is down should not be counted as real production value, but just report a production value of 0 watts.

### CODE REVIEW

**Comment by vincentwolsink** [comment]
I'm in doubt if we should fix this in the integration. Shouldn't we keep the measurements equal to the Envoy platform, to prevent deviation? And also basically this is a CT placement error that should be fixed.

**Comment by mnederlof** [comment]
I'll see if i can create a option for it in the settings. That way users can choose for themselves (and it'll be disabled by default).

For me it is not possible to wire it differently because of placement constraints in the fuse box / PV distributor.

**Comment by mnederlof** [comment]
Another great feature would be to integrate the [stream](http://envoy/stream/meter) endpoint, so you can have updates every second 😇

**Comment by vincentwolsink** [comment]
I looked at the stream endpoint before. But since I have an Envoy standard it is not available 😞

**Comment by mnederlof** [comment]
So now, i've added it in a entry option (you can do configure now), where you enable or disable this option.

You'd need to reload the plugin to make settings activate for now.

**Comment by vincentwolsink** [comment]
Are we sure it makes sense to update more often than every 60 seconds? For example the `devstatus` endpoint (where most of the metrics come from) does not even update every 60 seconds on the Envoy itself. I don't know about the production numbers on a metered Envoy, those might update more often, can you check @mnederlof?

I do think we should keep the default on 60, because of the large number of sensors (especially with a larger amount of solar panels/inverters). We don't want to put a big load on Home Assistant. If people then want to decrease the interval it is their own risk.

**Comment by catsmanac** [comment]
I'd vote for 60 as default as that seems common all around and my EU Envoy-S standard only provides 5 min updates anyway. Those that want to run faster will change it anyway.

**Comment by mnederlof** [comment]
Ah yes, i will change the default option value to use the SCAN_INTERVAL value from __init__ (and put it in const.py, while i'm at it. ), as this still is 60 seconds.

**Comment by mnederlof** [comment]
One could argue though, that we would want different intervals for different urls (depending on what we can fetch from which url), for example, the devstatus would not make sense more than once every 5 minutes, but fetching the current power production might make sense to get it more often (as for metered envoys, this is the current production value))
(that is not for this PR though, but just to share a thought.

**Comment by mnederlof** [comment]
I'm done with this PR though 😄 
I've changed the default value back to 60 (and it is configurable for all users now also)

**Comment by vincentwolsink** [comment]
@mnederlof Can you maybe just change the minimum amount to 5, so people cannot set an invalid value.

**Comment by vincentwolsink** [comment]
> One could argue though, that we would want different intervals for different urls (depending on what we can fetch from which url), for example, the devstatus would not make sense more than once every 5 minutes, but fetching the current power production might make sense to get it more often (as for metered envoys, this is the current production value)) (that is not for this PR though, but just to share a thought.

I was also thinking about this. Would be nice, but a lot more work 😄

**Pull request merged**
