### PR TITLE
Adding a product_id mapping to show more information about devices

### PR DESCRIPTION
**Pull request by mnederlof**
Not really sure if it is what i expected, but so far it looks like this:

envoy device:
image

inverter device:
image

relay device:
image

### CODE REVIEW

**Comment by mnederlof** [comment]
Open to suggestions for improvements 😄

**Comment by vincentwolsink** [comment]
Nice! I do think we need to lose the ‘-rXX’ in the mapping. I’ve seen multiple Envoys of the same type with different numbers there. Probably the revision or something.

**Comment by mnederlof** [comment]
Yeah, that is already done, while matching the hardware id; while resolving, it also loses the `800-` prepend in a second round of trying to match; see https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/pull/73/files#diff-0ac076ba3a419c22e8f034c216efb6b0347ddbac74545ec2eac8ceb10b067e4aR58

**Comment by vincentwolsink** [comment]
Ah yes indeed. 🙂

**Comment by vincentwolsink** [comment]
Now we need to crowdsource for product IDs I guess 😆

**Comment by mnederlof** [comment]
I'm just a bit sad the SKU with hardware id does not fit on one line for the inverter... 😄

**Comment by vincentwolsink** [comment]
If you drop the 800 and revision in the mapping already, it does 😜

**Comment by mnederlof** [comment]
> If you drop the 800 and revision in the mapping already, it does 😜

yeah, but that kind of defeats the point of showing it alltogether 🤔

**Comment by vincentwolsink** [comment]
Ah, you were talking about the screenshot. I was looking at the code. I agree but let’s keep it like this, it’s fine.

**Comment by mnederlof** [comment]
And the CT model is now also generated based on either the EnvoyData class name, or the ALIAS value set in that class (which is the same value for you, but it will now show to which data class it has resolved to)

**Review by vincentwolsink — APPROVED** [review]

**Pull request merged**
