### PR TITLE
Add more open per-inverter endpoint

### PR DESCRIPTION
**Pull request by krbaker**
First: As a recovering Sunpower user, *thank you*.  This integration brought back all of what I had with my sunpower integration and more.  

  I found one more endpoint that I haven't seen used before.  I think it has similar data to your per-inverter stats *but* I think its available for non-installer accounts (I can't 100% verify this, I don't have a non-installer account *but* it seems to work even when I don't fetch an installer token..  so I *think* it does).  This does change entity names in the backend which is a little frustrating as a user.
  I pulled a bit more of the data into sensors
  I made the sensors report 'unknown' when the envoy reports them 'gone' which seems the same as 'not communicating'.  The one thing I was seeing interestingly different was temperature going to 32f but I assume that is actually just a '0' which probably isn't really data.
  Lifetime power seems like its 'lifetime' since it was last configured with the envoy (sunpower seemed to actually pull a true lifetime of the inverter somehow..  :shrug: )
  
  This probably needs some debate before it goes in :-)

### CODE REVIEW

**Comment by mnederlof** [comment]
nice find on this url, how did you stumble upon this one ? 😃 

There is also more information for iq relays here:
```
    "999999960": {
        "devName": "nsrb",
        "sn": "999999998177",
        "active": true,
        "modGone": false,
        "channels": [
            {
                "chanEid": 9999999901,
                "created": 1732479942,
                "wattHours": {
                    "today": 0,
                    "yesterday": 0,
                    "week": 0
                },
                "watts": {
                    "now": 0,
                    "nowUsed": 0,
                    "max": 0
                },
                "lastReading": {
                    "eid": 9999999901,
                    "interval_type": 0,
                    "endDate": 1732479942,
                    "duration": 953,
                    "flags": 16,
                    "flags_hex": "0x0000000000000010",
                    "temperature": 33,
                    "acCurrOffset": -15,
                    "VrmsL1N": 225868,
                    "VrmsL2N": 204,
                    "VrmsL3N": 0,
                    "freqInmHz": 50017,
                    "stateChngCnt": 1,
                    "vrmsB1L12": 0,
                    "vrmsB2L12": 0
                },
                "lifetime": {}
            }
        ]
    },
```

so now we finally know what voltage and frequency the iq relay is reading 😇

**Comment by mnederlof** [comment]
also, i have a installer account, so cannot verify if url https://envoy/ivp/pdm/device_data is a installer only endpoint

**Comment by catsmanac** [comment]
Tried it with my home-owner account on my Envoy non-metered and both ivp/pdm/device_data and /ivp/pdm/energy work fine.

**Comment by vincentwolsink** [comment]
This endpoint indeed works with an home owner account, great! I will see if we can switch over, preferably maintaining all the sensor IDs so people don't loose their history.

Thanks for you contribution and the new endpoint @krbaker ! 😃

**Comment by krbaker** [comment]
> This endpoint indeed works with an home owner account, great! I will see if we can switch over, preferably maintaining all the sensor IDs so people don't loose their history.
> 
> Thanks for you contribution and the new endpoint @krbaker ! 😃

Cool to see there is even more data here, I don't have an enphase battery system. 

Just in case I don't want to get my source in trouble but it started from this thread: https://support.enphase.com/s/question/0D53m000095MFl3CAG/is-there-anywhere-where-i-can-view-full-local-api-documentation-for-my-envoy

**Comment by krbaker** [comment]
Oh, one thing I should mention.  Things like the temperature and wattage 'stick' at the last reported value.  I used the 'gone' status to make the values change to 'unavailable' when a panel is offline.  This is I think slightly different than the other values (I noticed temperature goes to 0c when the panel is offline - I think).  Questionable if this matches what folks want from this plugin.

**Pull request merged**
