### PR TITLE
Refactoring how data is fetched and collected by datacoordinator.update

### PR DESCRIPTION
**Pull request by mnederlof**
Added methods for backward compatibility (which fetches the data from the EnvoyData class)

Also renamed some properties to match the EntityDescription.key as defined in const.py

This also removes the `__getattr__` method from the `EnvoyReader` class, making it a more straight forward class to read.

### CODE REVIEW

**Comment by mnederlof** [comment]
Please test if it works for you too before merging 😄

**Comment by vincentwolsink** [comment]
```
Traceback (most recent call last):
  File "/Users/vincent/devel/home_assistant_enphase_envoy_installer/custom_components/enphase_envoy/envoy_reader.py", line 560, in <module>
    class EnvoyReader:
  File "/Users/vincent/devel/home_assistant_enphase_envoy_installer/custom_components/enphase_envoy/envoy_reader.py", line 1238, in EnvoyReader
    battery_storage = _async_get_property("battery_storage")
TypeError: 'staticmethod' object is not callable
```

**Comment by mnederlof** [comment]
> ```
> Traceback (most recent call last):
>   File "/Users/vincent/devel/home_assistant_enphase_envoy_installer/custom_components/enphase_envoy/envoy_reader.py", line 560, in <module>
>     class EnvoyReader:
>   File "/Users/vincent/devel/home_assistant_enphase_envoy_installer/custom_components/enphase_envoy/envoy_reader.py", line 1238, in EnvoyReader
>     battery_storage = _async_get_property("battery_storage")
> TypeError: 'staticmethod' object is not callable
> ```

That is weird, i did not encounter this issue, will test again, or do it differently...

**Comment by mnederlof** [comment]
I've moved the _async_get_property method out of the class. it should work better now :)

**Review by vincentwolsink — APPROVED** [review]

**Pull request merged**
