### PR TITLE
Add missing places to expose detected envoy model

### PR DESCRIPTION
**Pull request by mnederlof**

### CODE REVIEW

**Comment by vincentwolsink** [comment]
Seems I missed some places indeed. Didn't remember it is there for all sensor types.

**Comment by vincentwolsink** [comment]
I think it should be like this (see latest commit), to keep the model "Inverter" and "Relay".

**Comment by mnederlof** [comment]
Yes, that's better 😄

**Comment by vincentwolsink** [comment]
Would be nice if we could also expose the inverter product name. But could not find anything for that yet (also no PN to product name mapping anywhere)

**Comment by mnederlof** [comment]
Yeah, i thought of that too, but then we'd be creating our own list/mapping of part_num to readable product name. For the ones we're having we could start with that though 😄 

Maybe there is something on the enlighten interface somewhere that we could retrospect and/or reproduce, have to look at that later.

**Review by vincentwolsink — APPROVED** [review]

**Comment by mnederlof** [comment]
> Yeah, i thought of that too, but then we'd be creating our own list/mapping of part_num to readable product name. For the ones we're having we could start with that though 😄
> 
> Maybe there is something on the enlighten interface somewhere that we could retrospect and/or reproduce, have to look at that later.

I could not find anything in the enlighten interface, so my best bet would be to keep a static list

this is my list at least..
```
800-00654-r08 (Envoy-S-Metered-EU)
800-01736-r02 (IQ7+; IQ7PLUS-72-M-INT)
800-00598-r04 (IQ Relay 1-phase; Q-RELAY-1P-INT)
```

**Comment by vincentwolsink** [comment]
```
800-00656-r06 (Envoy-S-Standard-EU)
800-01359-r02 (IQ8+; IQ8PLUS-72-M-INT)
```

Although it might be nice to keep the Envoy model as the detected one. Also for (easy) debugging, maybe.

**Pull request merged**
